# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHP-G4LZtiBt94EI5Yswko-cDWIJwKIh
"""

import joblib
import gradio as gr
import pickle

# Charger modèle et vectorizer
model = joblib.load('spam_classifier.pkl')
vectorizer = joblib.load('tfidf_vectorizer.pkl')

# Charger fonctions de preprocessing
with open('preprocessing_config.pkl', 'rb') as f:
    preprocessing_config = pickle.load(f)

# Récupérer la fonction de preprocessing générale (exemple)
preprocess_spam = preprocessing_config['preprocess_spam']
preprocess_ham = preprocessing_config['preprocess_ham']

def predict_sms(text):
    # Ici tu appliques ton preprocessing sur le texte
    # exemple simple si tu as une fonction unique
    text_clean = preprocess_spam(text)  # ou preprocess_ham selon ton choix
    X = vectorizer.transform([text_clean])
    pred = model.predict(X)[0]
    prob = model.predict_proba(X).max()
    return {"prediction": pred, "probability": round(prob, 3)}

# Interface Gradio
iface = gr.Interface(
    fn=predict_sms,
    inputs="text",
    outputs=["label", "number"],
    title="SMS Spam Classifier",
    description="Classifie un SMS en ham ou spam"
)

iface.launch()